import "@/styles/global.css";
import { Nav } from "@/components/Nav";
import { NavContextProvider } from "@/utils/navContextProvider";
import { Suspense, unstable_ViewTransition as ViewTransition } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransition>
      <html lang="en">
        <body className="grid">
          <NavContextProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <Nav />
            </Suspense>
            {children}
          </NavContextProvider>
        </body>
      </html>
    </ViewTransition>
  );
}
