import "@/styles/global.css";
import { Nav } from "@/components/Nav";
import { NavContextProvider } from "@/utils/navContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="grid">
        <NavContextProvider>
          <Nav />
          {children}
        </NavContextProvider>
      </body>
    </html>
  );
}
